import com.kingdee.bos.webapi.sdk.K3CloudApi;

public class Retail {
    public static void main(String[] args) throws Exception {
        K3CloudApi client = new K3CloudApi();
        String formId = "CMK_LS_Retail";
//        String jsonData ="{\"NeedUpDateFields\":[],\"NeedReturnFields\":[],\"IsDeleteEntry\":\"true\",\"SubSystemId\":\"\",\"IsVerifyBaseDataField\":\"false\",\"IsEntryBatchFill\":\"true\",\"ValidateFlag\":\"true\",\"NumberSearch\":\"true\",\"IsAutoAdjustField\":\"false\",\"InterationFlags\":\"\",\"IgnoreInterationFlag\":\"\",\"Model\":{\"FID\":0,\"FRefundStatus\":\"\",\"FBillNo\":\"D7952144010334\",\"FDate\":\"2024-01-02 11:33:22\",\"FDocumentStatus\":\"C\",\"FBillStatus\":\"S\",\"FBillTypeID\":{\"FNUMBER\":\"SelfhelpShop\"},\"FSalOrgId\":{\"FNUMBER\":\"10000\"},\"FBranchId\":{\"FNumber\":\"R3S-D795\"},\"FLocalCurId\":{\"FNUMBER\":\"PRE001\"},\"FBaseCurID\":{\"FNUMBER\":\"PRE001\"},\"FCashier\":{\"FNUMBER\":\"R3S-D795\"},\"FCustomerId\":{\"FNUMBER\":\"CUST0211\"},\"FExchangeTypeID\":{\"FNUMBER\":\"HLTX01_SYS\"},\"FVIPName\":\"\",\"FTotalAmount\":\"69.000\",\"FReceAmount\":\"69.000\",\"FTotalRealAmt\":\"69.000\",\"FDiscountAmount\":\"0.000\",\"FStartTime\":\"2024-01-02 11:33:22\",\"FEndtime\":\"2024-01-02 11:33:22\",\"FCreatorId\":{\"FUserName\":\"\\\\u534e\\\\u5c79\"},\"FCheckId\":{\"FUserName\":\"\\\\u534e\\\\u5c79\"},\"FModifierId\":{\"FUserName\":\"\\\\u534e\\\\u5c79\"},\"FPickWay\":\"1\",\"FCreateDate\":\"2024-01-02 11:33:22\",\"FCheckDate\":\"2024-01-02 11:33:22\",\"FModifyDate\":\"2024-01-02 03:34:38\",\"FUUID\":\"201b2c03-f0a6-47e1-a4f9-63a512dca757\",\"FSaleOption\":\"1\",\"FEntity\":[{\"FEntryIsInstock\":false,\"FEntryIsPackage\":false,\"FCOMTYPEID\":{\"FNUMBER\":\"1\"},\"FSUBSIDYFLAG\":false,\"FGoodssnf\":false,\"FQty\":1.0,\"FUnitID\":{\"FNumber\":\"Pcs\"},\"FBaseUnitID\":{\"FNumber\":\"Pcs\"},\"FMaterialId\":{\"FNUMBER\":\"6958985024280\"},\"FBarCode\":\"6958985024280\",\"FStockStatusID\":{\"FNUMBER\":\"KCZT01_SYS\"},\"FBaseQty\":1.0,\"FPrice\":69.0,\"FDiscountRate\":\"0.00\",\"FDiscountPrice\":69.0,\"FAmount\":69.0,\"FBalAmount\":69.0,\"FSECCOEFFICIENT\":1.0,\"FUNITRATE\":1.0,\"FStockOrgId\":{\"FNUMBER\":\"10000\"},\"FStockId\":{\"FNUMBER\":\"LZ-JT040\"},\"FOwnerId\":{\"FNUMBER\":\"R3S-D795\"},\"FMaterialName\":null,\"FTaxAmount\":\"0.000\",\"FDeliverStatus\":\"1\",\"FDELIVERTIME\":\"2024-01-02 11:33:22\",\"FTaxRate\":\"0\",\"FRealPrice\":69.0,\"FRealAmount\":69.0,\"FIsPresent\":0,\"FOwnerTypeId\":\"BD_OwnerOrg\",\"FRetQty\":0,\"FRETREASONID\":null}],\"FFinEntity\":[{\"FRate\":1,\"FSettleId\":{\"FNUMBER\":\"15\"},\"FSettleCurrId\":{\"FNUMBER\":\"PRE001\"},\"FSettleAmount\":\"69.000\"}]}}";
        String jsonData = "{\"NeedUpDateFields\":[],\"NeedReturnFields\":[],\"IsDeleteEntry\":\"true\",\"SubSystemId\":\"\",\"IsVerifyBaseDataField\":\"false\",\"IsEntryBatchFill\":\"true\",\"ValidateFlag\":\"true\",\"NumberSearch\":\"true\",\"IsAutoAdjustField\":\"false\",\"InterationFlags\":\"\",\"IgnoreInterationFlag\":\"\",\"IsControlPrecision\":\"false\",\"ValidateRepeatJson\":\"false\",\"Model\":{\"FID\":0,\"FBillTypeID\":{\"FNUMBER\":\"BZLSD\"},\"FSalOrgId\":{\"FNumber\":\"20010\"},\"FLocalCurId\":{\"FNUMBER\":\"PRE001\"},\"FExchangeTypeID\":{\"FNUMBER\":\"HLTX01_SYS\"},\"FTotalAmount\":690.00,\"FDiscountAmount\":0.0,\"FReceAmount\":690.00,\"FCreatorId\":{\"FUserID\":16394},\"FCreateDate\":\"2024-01-17 10:44:24\",\"FIsGroupOrder\":\"0\",\"FSaleOption\":\"1\",\"FTotalRealAmt\":0.0,\"FIsUpdateVIPCons\":\"0\",\"FISPRICEEXCLUDETAX\":\"0\",\"FTOTALTAXAMOUNT\":0.0,\"FTOTALNOTINTAXAMT\":0.0,\"FExchangeRate\":0.0,\"FIsDaySettle\":\"0\",\"FWHOLEQTY\":0.0,\"F_ora_Assistant\":{\"FNumber\":\"001\"},\"FEntity\":[{\"FMaterialId\":{\"FNUMBER\":\"0016027740140-10\"},\"FBarCode\":\"0016027740140-10\",\"FStockStatusID\":{\"FNUMBER\":\"KCZT01_SYS\"},\"FStockOrgId\":{\"FNumber\":\"20010\"},\"FStockId\":{\"FNUMBER\":\"SYSM00003\"},\"FOwnerTypeId\":\"BD_OwnerOrg\",\"FOwnerId\":{\"FNumber\":\"20010\"},\"FBaseUnitID\":{\"FNumber\":\"Pcs\"},\"FUnitID\":{\"FNumber\":\"Pcs\"},\"FQty\":10.0,\"FBaseQty\":10.0,\"FAuxUnitQty\":10.0,\"FPrice\":69.0,\"FDiscountRate\":100.0,\"FDiscountPrice\":69.0,\"FAmount\":690.00,\"FBalAmount\":690.00,\"FBaseRetQty\":0.0,\"FRetQty\":0.0,\"FIsPresent\":\"0\",\"FSourceBillNo\":\"\",\"FSourceBillType\":\"\",\"FPoint\":0.0,\"FSUBSIDYFLAG\":false,\"FSubsidy\":0.0,\"FSubsidySum\":0.0,\"FGoodssnf\":false,\"FUNITRATE\":1.0,\"FSECCOEFFICIENT\":1.0,\"FSecPrice\":0.0,\"FSNQty\":0.0,\"FCOMTYPEID\":{\"FNUMBER\":\"1\"},\"FUNITNUM\":0.0,\"FUNITNOM\":0.0,\"FBASEPRICE\":0.0,\"FAUXUNITNUM\":0.0,\"FAUXUNITNOM\":0.0,\"FEXPPERIOD\":0.0,\"FTaxRate\":13.0,\"FNotInTaxAmt\":0.0,\"FTaxAmount\":0.0,\"FRealPrice\":0.0,\"FRealAmount\":0.0,\"FProPrice\":0.0,\"FProAmount\":0.0,\"FEntryIsDaySettle\":\"0\",\"FEntryIsPackage\":false,\"FEntryIsInstock\":false,\"FEDISCRATE\":0.0,\"FInvoiceTaxRate\":0.0,\"F_ora_Qty\":0.0}]}}";
        String result = client.save(formId, jsonData);
        System.out.println(result);
    }
}